# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fde9b315b98701201e1bf22a6a0594371a028a8f2c49638a12f649191f190a8de6626f1c17be12fe37040a7d6f6130657d302384b5e27b539cc2a8113a14802d

test:
  secret_key_base: 9ca37e0c2f3db0c089bd578d9e789f7363525fecf22177e399e96d052a94d704ff78fe58ba7eb035f22d138468ef8de4b54c694253e716bb0237241b3b1def1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
